extends SceneTree

var failures: Array[String] = []
var release_count := 0
var reward_count := 0
var near_complete_count := 0
var gate_events: Array[bool] = []
var adaptation_start_count := 0

func _initialize() -> void:
	call_deferred("_run")

func _run() -> void:
	var director := TutorialDirector.new()
	director.guide_released.connect(func() -> void: release_count += 1)
	director.reward_unlocked.connect(func() -> void: reward_count += 1)
	director.near_complete_reached.connect(func() -> void: near_complete_count += 1)
	director.goal_acceptance_changed.connect(func(value: bool) -> void: gate_events.append(value))
	director.adaptation_started.connect(func() -> void: adaptation_start_count += 1)
	director.begin_run(true, 100)
	_check(director.stage == TutorialDirector.Stage.WELCOME, "tutorial offers a choice", failures)
	_check(not director.goal_accepting and gate_events == [false], "goal starts closed", failures)
	director.advance(20.0, LightField.Mode.CLEAR, 1.0, 0.0)
	_check(director.stage == TutorialDirector.Stage.WELCOME, "choice waits for player", failures)
	director.choose_tutorial()
	_check(director.stage == TutorialDirector.Stage.SHUTTER, "choice starts shutter lesson", failures)
	director.advance(0.1, LightField.Mode.CLEAR, 1.0, 0.0)
	director.advance(TutorialDirector.DIALOGUE_PAUSE_SECONDS, LightField.Mode.CLEAR, 0.0, 0.0)
	_check(director.stage == TutorialDirector.Stage.ADAPTATION and adaptation_start_count == 1, "closing shutter starts reveal", failures)
	director.advance(TutorialDirector.DIALOGUE_PAUSE_SECONDS, LightField.Mode.CLEAR, 0.0, 0.0)
	director.request_continue()
	_check(director.status_text.contains("adrift"), "reveal mentions jam theme", failures)
	director.advance(TutorialDirector.DIALOGUE_PAUSE_SECONDS, LightField.Mode.CLEAR, 0.0, 0.0)
	director.request_continue()
	_check(director.status_text.contains("solid"), "reveal clarifies ground remains solid", failures)
	director.advance(TutorialDirector.DIALOGUE_PAUSE_SECONDS, LightField.Mode.CLEAR, 0.0, 0.0)
	director.request_continue()
	_check(director.stage == TutorialDirector.Stage.REVEAL_WAIT and director.adaptation_progress == 1.0, "full reveal waits for player", failures)
	_check(director.status_text.contains("jumpscares"), "reveal reassures player", failures)
	director.advance(TutorialDirector.REVEAL_HOLD_SECONDS - 0.1, LightField.Mode.CLEAR, 1.0, 1.0)
	_check(director.stage == TutorialDirector.Stage.REVEAL_WAIT, "shutter remains closed for reveal hold", failures)
	director.advance(0.2, LightField.Mode.CLEAR, 1.0, 1.0)
	_check(director.stage == TutorialDirector.Stage.JAR_NEUTRAL, "reopening shutter begins neutral jar observation", failures)
	director.advance(TutorialDirector.JAR_OBSERVATION_SECONDS, LightField.Mode.CLEAR, 1.0, 1.0)
	director.request_continue()
	_check(director.stage == TutorialDirector.Stage.JAR_BLUE, "neutral observation precedes blue demo", failures)
	director.advance(TutorialDirector.JAR_OBSERVATION_SECONDS, LightField.Mode.BLUE, 1.0, 1.0)
	director.request_continue()
	_check(director.stage == TutorialDirector.Stage.JAR_ORANGE and director.guide_state == TutorialDirector.GuideState.DORMANT, "blue calms guide before orange", failures)
	director.advance(TutorialDirector.JAR_OBSERVATION_SECONDS, LightField.Mode.ORANGE, 1.0, 1.0)
	director.request_continue()
	_check(director.stage == TutorialDirector.Stage.GUIDE and release_count == 1, "orange releases guide once", failures)
	director.advance(TutorialDirector.GUIDE_SECONDS, LightField.Mode.ORANGE, 1.0, 1.0)
	director.request_continue()
	director.advance(TutorialDirector.GROUPS_SECONDS, LightField.Mode.ORANGE, 1.0, 1.0)
	director.request_continue()
	_check(director.stage == TutorialDirector.Stage.FREE_PLAY and director.goal_accepting, "lesson enters free play and opens goal", failures)
	_check(not director.status_text.contains("either shrine"), "solo tutorial names one shrine", failures)
	_check(gate_events == [false, true], "goal gate emits only transitions", failures)
	_check(director.ukon_nearby_line().contains("hurt"), "free-play Ukon reassures", failures)
	director.observe_score(24)
	_check(director.ukon_nearby_line().contains("Take your time"), "early progress stays low pressure and gives light lore", failures)
	director.observe_score(25)
	_check(director.ukon_nearby_line(1).contains("light vein"), "quarter progress rotates a gentle tip", failures)
	director.observe_score(50)
	_check(director.ukon_nearby_line().contains("Half the grove"), "half progress congratulates and offers a tip", failures)
	director.observe_score(60)
	_check(director.reward_is_unlocked and reward_count == 1, "existing sandbox milestone still unlocks at 60 percent", failures)
	director.observe_score(80)
	_check(director.near_complete_milestone_reached and near_complete_count == 1 and director.ukon_nearby_line().contains("optional"), "80 percent frames completion as optional", failures)
	_check(director.ukon_nearby_line().contains("Play"), "80 percent points to saved completion times", failures)
	director.observe_score(95)
	_check(director.ukon_nearby_line().contains("Nearly everyone"), "95 percent gives a near-complete message", failures)
	director.observe_score(100)
	_check(director.ukon_nearby_line().contains("Every mushi") and director.ukon_nearby_line().contains("wonderful migration"), "full completion gets stronger congratulations", failures)
	director.begin_run(true, 20)
	director.skip()
	director.skip()
	_check(director.stage == TutorialDirector.Stage.FREE_PLAY and release_count == 2, "skip is idempotent", failures)
	director.begin_run(true, 20)
	director.choose_tutorial()
	director.advance(TutorialDirector.DIALOGUE_PAUSE_SECONDS, LightField.Mode.CLEAR, 0.0, 0.0)
	_check(director.stage == TutorialDirector.Stage.ADAPTATION, "already closed shutter starts adaptation after choice", failures)
	director.begin_run(false, 10)
	_check(director.stage == TutorialDirector.Stage.FREE_PLAY and director.goal_accepting, "disabled tutorial begins in free play", failures)
	_check(director.ukon_nearby_line().is_empty(), "modes without the tutorial guide do not show Ukon dialogue", failures)
	for failure in failures:
		push_error(failure)
	print("TUTORIAL_DIRECTOR_CHECKS failures=%d" % failures.size())
	quit(0 if failures.is_empty() else 1)

func _check(condition: bool, message: String, errors: Array[String]) -> void:
	if not condition:
		errors.append(message)
